In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('/content/drive/MyDrive/프로젝트응용(신동준, 이재훈, 최민규)/data/모델용데이터/train_v1.csv')
df.shape

(34728, 16)

In [4]:
df.head()

,AGE_GRP,GENDER,TRAVEL_MONTH,TRAVEL_PERIOD,NTvsCT,EXPLODvsCHPLOD,RESTvsACT,UNKvsK,MVMN_NM,TRAVEL_MISSION_CHECK1,TRAVEL_MISSION_CHECK2,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,budget,VISIT_AREA_NM,DGSTFN
0,60.0,여,10,3,2,1,2,2,대중교통 등,종교/성지 순례,역사 유적지 방문,새로운 경험 추구,"역사 탐방, 문화적 경험 등 교육적 동기",28.631658,수도국산 달동네박물관,5.0
1,60.0,여,10,3,2,1,2,2,대중교통 등,종교/성지 순례,역사 유적지 방문,새로운 경험 추구,"역사 탐방, 문화적 경험 등 교육적 동기",28.631658,인천내리교회,5.0
2,60.0,여,10,3,2,1,2,2,대중교통 등,종교/성지 순례,역사 유적지 방문,새로운 경험 추구,"역사 탐방, 문화적 경험 등 교육적 동기",28.631658,부평문화의거리,4.0
3,60.0,여,10,3,2,1,2,2,대중교통 등,종교/성지 순례,역사 유적지 방문,새로운 경험 추구,"역사 탐방, 문화적 경험 등 교육적 동기",28.631658,인천배다리헌책방거리,4.0
4,60.0,여,10,3,2,1,2,2,대중교통 등,종교/성지 순례,역사 유적지 방문,새로운 경험 추구,"역사 탐방, 문화적 경험 등 교육적 동기",28.631658,인천개항장 근대건축전시관,5.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34728 entries, 0 to 34727
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   AGE_GRP                34728 non-null  float64
 1   GENDER                 34728 non-null  object
 2   TRAVEL_MONTH           34728 non-null  int64
 3   TRAVEL_PERIOD          34728 non-null  int64
 4   NTvsCT                 34728 non-null  int64
 5   EXPLODvsCHPLOD         34728 non-null  int64
 6   RESTvsACT              34728 non-null  int64
 7   UNKvsK                 34728 non-null  int64
 8   MVMN_NM                34728 non-null  object
 9   TRAVEL_MISSION_CHECK1  34728 non-null  object
 10  TRAVEL_MISSION_CHECK2  34728 non-null  object
 11  TRAVEL_MOTIVE_1        34728 non-null  object
 12  TRAVEL_MOTIVE_2        34728 non-null  object
 13  budget                 34728 non-null  float64
 14  VISIT_AREA_NM          34728 non-null  object
 15  DGSTFN                 34728 non-null  float64
dtypes: float64(3), int64(6), object(7)
memory usage: 4.2+ MB

In [23]:
df_ad = pd.read_csv('/content/drive/MyDrive/프로젝트응용(신동준, 이재훈, 최민규)/data/전처리/주소 통합(4).csv')
df_ad.shape

(30862, 25)

In [24]:
df_ad.columns

Index(['AGE_GRP', 'GENDER', 'TRAVEL_MONTH', 'TRAVEL_PERIOD', 'NTvsCT',
       'EXPLODvsCHPLOD', 'RESTvsACT', 'UNKvsK', 'MVMN_NM',
       'TRAVEL_MISSION_CHECK1', 'TRAVEL_MISSION_CHECK2', 'TRAVEL_MOTIVE_1',
       'TRAVEL_MOTIVE_2', 'TRAVEL_MOTIVE_3', 'budget', 'VISIT_AREA_NM',
       'DGSTFN', 'ROAD_NM_ADDR', 'LOTNO_ADDR', 'X_COORD', 'Y_COORD', 'address',
       'LONGEST_ADDR', 'INTEGRATED_REGION', 'INTEGRATED_CITY'],
      dtype='object')

In [25]:
df_ad = df_ad.drop(columns=['TRAVEL_MOTIVE_3', 'ROAD_NM_ADDR', 'LOTNO_ADDR', 'X_COORD', 'Y_COORD', 'address'])

In [26]:
df_ad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30862 entries, 0 to 30861
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   AGE_GRP                30862 non-null  float64
 1   GENDER                 30862 non-null  object
 2   TRAVEL_MONTH           30862 non-null  int64
 3   TRAVEL_PERIOD          30862 non-null  int64
 4   NTvsCT                 30862 non-null  int64
 5   EXPLODvsCHPLOD         30862 non-null  int64
 6   RESTvsACT              30862 non-null  int64
 7   UNKvsK                 30862 non-null  int64
 8   MVMN_NM                30862 non-null  object
 9   TRAVEL_MISSION_CHECK1  30862 non-null  int64
 10  TRAVEL_MISSION_CHECK2  30862 non-null  int64
 11  TRAVEL_MOTIVE_1        30862 non-null  float64
 12  TRAVEL_MOTIVE_2        30862 non-null  float64
 13  budget                 30862 non-null  float64
 14  VISIT_AREA_NM          30862 non-null  object
 15  DGSTFN                 30862 non-null  float64
 16  LONGEST_ADDR           30862 non-null  object
 17  INTEGRATED_REGION      30862 non-null  object
 18  INTEGRATED_CITY        22528 non-null  object
dtypes: float64(5), int64(8), object(6)
memory usage: 4.5+ MB

In [27]:
df_ad.loc[(df_ad['INTEGRATED_REGION'].isin(['서울특별시', '대전광역시', '대구광역시', '울산광역시', '부산광역시', '세종특별자치시', '광주광역시', '인천광역시'])) & (df_ad['INTEGRATED_CITY'].notnull())]

,AGE_GRP,GENDER,TRAVEL_MONTH,TRAVEL_PERIOD,NTvsCT,EXPLODvsCHPLOD,RESTvsACT,UNKvsK,MVMN_NM,TRAVEL_MISSION_CHECK1,TRAVEL_MISSION_CHECK2,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,budget,VISIT_AREA_NM,DGSTFN,LONGEST_ADDR,INTEGRATED_REGION,INTEGRATED_CITY
31,30.0,여,10,1,1,2,1,3,대중교통 등,1,26,7.0,2.0,65000.0,아트박스 위례점,3.0,경기 파주시 탄현면 성동리 84,서울특별시,파주시
32,30.0,여,10,1,1,2,1,3,대중교통 등,1,26,7.0,2.0,65000.0,메가MGC커피 위례와이즈더샵점,5.0,경기 파주시 탄현면 성동리 93-2,서울특별시,파주시
34,30.0,여,10,1,1,2,1,3,대중교통 등,1,26,7.0,2.0,65000.0,다이소 위례본점,5.0,경기 파주시 탄현면 법흥리 1652-239,서울특별시,파주시
199,40.0,여,10,1,1,2,1,1,대중교통 등,1,6,1.0,4.0,50500.0,차이797,3.0,서울 송파구 올림픽로 269 롯데캐슬 F2 차이797,서울특별시,칠곡군
209,20.0,여,10,1,1,1,3,1,대중교통 등,22,4,7.0,1.0,64800.0,북한산둘레길 마실길9구간,3.0,경기도 고양시 덕양구 북한산로 502,서울특별시,고양시
406,20.0,남,10,2,1,1,3,1,대중교통 등,23,28,1.0,2.0,273300.0,남산서울타워,5.0,제주특별자치도 제주시 조천읍 교래1길 45,서울특별시,제주시
701,20.0,남,10,1,1,1,1,3,대중교통 등,26,28,1.0,8.0,30600.0,인왕산 범바위,5.0,제주특별자치도 제주시 구좌읍 문주란로 121-1,서울특별시,제주시
877,20.0,남,10,2,3,1,1,3,대중교통 등,2,4,4.0,2.0,184500.0,라인프렌즈 플래그십스토어 강남점,3.0,경기 과천시 과천동 449-5,서울특별시,과천시
1334,40.0,남,10,2,1,1,3,1,대중교통 등,1,4,1.0,4.0,79500.0,스타벅스 장한평역점,4.0,제주특별자치도 제주시 구좌읍 평대리 3322,서울특별시,제주시
1498,40.0,여,10,1,3,1,1,1,대중교통 등,3,6,8.0,1.0,35000.0,흥국생명 본사금융플라자,3.0,전북특별자치도 익산시 금마면 신용리 722,서울특별시,익산시
1669,20.0,남,10,2,2,2,3,2,대중교통 등,3,6,6.0,8.0,48041.0,동인천 개항거리(개항지+일본풍거리등),4.0,인천 중구 신포로15번길 76 일대 거리들,인천광역시,여수시
2520,30.0,여,10,1,3,2,3,1,대중교통 등,1,9,2.0,1.0,51100.0,인천 개항의 거리,1.0,강원특별자치도 춘천시 퇴계동 1152-1,인천광역시,춘천시
2521,30.0,여,10,1,3,2,3,1,대중교통 등,1,9,2.0,1.0,51100.0,차이나타운 중화거리,5.0,강원특별자치도 춘천시 신북읍 천전리 99-13,인천광역시,춘천시
2529,30.0,남,10,2,1,2,1,3,대중교통 등,3,6,2.0,1.0,86600.0,남산,5.0,제주특별자치도 서귀포시 안덕면 사계북로41번길 192,서울특별시,서귀포시
3222,30.0,남,10,2,1,1,1,1,자가용,22,1,1.0,7.0,85000.0,인천차이나타운,5.0,제주특별자치도 서귀포시 서호중로 65,인천광역시,서귀포시
5694,20.0,여,10,1,3,1,3,1,대중교통 등,21,24,1.0,2.0,85800.0,대건명가돼지국밥,5.0,제주특별자치도 제주시 한림읍 월림리 2364,부산광역시,제주시
6030,30.0,여,10,2,1,1,3,1,대중교통 등,28,9,6.0,1.0,278610.0,봉래산,5.0,경기도 포천시 신북면 청신로947번길 35,부산광역시,포천시
6690,20.0,남,10,1,1,1,1,1,대중교통 등,4,22,1.0,7.0,5500.0,다솜국수,4.0,제주특별자치도 제주시 구좌읍 송당리 2263,세종특별자치시,제주시
13707,30.0,여,10,3,1,1,2,1,대중교통 등,23,21,4.0,6.0,497415.0,트윗젤,3.0,서울특별시 강서구 하늘길 112,서울특별시,과천시
15443,20.0,여,8,2,1,2,2,1,대중교통 등,21,1,7.0,2.0,100100.0,코업시티호텔 성산,5.0,제주특별자치도 서귀포시 성산읍 성산등용로 28,서울특별시,서귀포시

In [28]:
# 마지막으로 조금 덜 조정된 것들 수정 조금 +
df_ad.loc[df_ad['LONGEST_ADDR'].str.startswith('경기'), 'INTEGRATED_REGION'] = '경기도'
df_ad.loc[df_ad['LONGEST_ADDR'].str.startswith('제주'), 'INTEGRATED_REGION'] = '제주특별자치도'
df_ad.loc[df_ad['LONGEST_ADDR'].str.startswith('경북'), 'INTEGRATED_REGION'] = '경상북도'
df_ad.loc[df_ad['LONGEST_ADDR'].str.startswith('전북'), 'INTEGRATED_REGION'] = '전북특별자치도'

In [29]:
df_ad.loc[(df_ad['INTEGRATED_REGION'].isin(['서울특별시', '대전광역시', '대구광역시', '울산광역시', '부산광역시', '세종특별자치시', '광주광역시', '인천광역시'])) & (df_ad['INTEGRATED_CITY'].notnull())]

,AGE_GRP,GENDER,TRAVEL_MONTH,TRAVEL_PERIOD,NTvsCT,EXPLODvsCHPLOD,RESTvsACT,UNKvsK,MVMN_NM,TRAVEL_MISSION_CHECK1,TRAVEL_MISSION_CHECK2,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,budget,VISIT_AREA_NM,DGSTFN,LONGEST_ADDR,INTEGRATED_REGION,INTEGRATED_CITY
199,40.0,여,10,1,1,2,1,1,대중교통 등,1,6,1.0,4.0,50500.0,차이797,3.0,서울 송파구 올림픽로 269 롯데캐슬 F2 차이797,서울특별시,칠곡군
1669,20.0,남,10,2,2,2,3,2,대중교통 등,3,6,6.0,8.0,48041.0,동인천 개항거리(개항지+일본풍거리등),4.0,인천 중구 신포로15번길 76 일대 거리들,인천광역시,여수시
2520,30.0,여,10,1,3,2,3,1,대중교통 등,1,9,2.0,1.0,51100.0,인천 개항의 거리,1.0,강원특별자치도 춘천시 퇴계동 1152-1,인천광역시,춘천시
2521,30.0,여,10,1,3,2,3,1,대중교통 등,1,9,2.0,1.0,51100.0,차이나타운 중화거리,5.0,강원특별자치도 춘천시 신북읍 천전리 99-13,인천광역시,춘천시
13707,30.0,여,10,3,1,1,2,1,대중교통 등,23,21,4.0,6.0,497415.0,트윗젤,3.0,서울특별시 강서구 하늘길 112,서울특별시,과천시

In [30]:
# 마지막으로 조금 덜 조정된 것들 수정 조금 +
df_ad.loc[df_ad['LONGEST_ADDR'].str.startswith('경기'), 'INTEGRATED_REGION'] = '경기도'
df_ad.loc[df_ad['LONGEST_ADDR'].str.startswith('제주'), 'INTEGRATED_REGION'] = '제주특별자치도'
df_ad.loc[df_ad['LONGEST_ADDR'].str.startswith('경북'), 'INTEGRATED_REGION'] = '경상북도'
df_ad.loc[df_ad['LONGEST_ADDR'].str.startswith('전북'), 'INTEGRATED_REGION'] = '전북특별자치도'

# 이건 더 안된 것들. 아예 제거가 나을 듯.
# 조건을 만족하는 행의 인덱스를 제거하는 코드
df_ad = df_ad.drop(df_ad.loc[(df_ad['INTEGRATED_REGION'].isin(['서울특별시', '인천광역시'])) & (df_ad['INTEGRATED_CITY'].notna())].index)

df_ad['INTEGRATED_CITY'] = df_ad['INTEGRATED_CITY'].fillna('미선택')

df_ad['AGE_GRP'] = df_ad['AGE_GRP'].astype(int)

df_ad = df_ad[['INTEGRATED_REGION', 'INTEGRATED_CITY', 'AGE_GRP', 'GENDER', 'TRAVEL_MONTH', 'TRAVEL_PERIOD', 'NTvsCT', 'EXPLODvsCHPLOD', 'RESTvsACT', 'UNKvsK',
             'MVMN_NM', 'TRAVEL_MISSION_CHECK1', 'TRAVEL_MISSION_CHECK2', 'TRAVEL_MOTIVE_1', 'TRAVEL_MOTIVE_2', 'budget',
             'VISIT_AREA_NM', 'DGSTFN', 'LONGEST_ADDR']]

In [ ]:
# df_ad.to_csv('/content/drive/MyDrive/프로젝트응용(신동준, 이재훈, 최민규)/data/전처리/train_add_last.csv', index=False)

In [32]:
df_ad.shape

(30857, 19)

In [35]:
df_merge_add = pd.merge(df, df_ad, on='VISIT_AREA_NM', how='right')
df_merge_add.shape

(218766, 34)

# 불러오기

In [ ]:
df_train = pd.read_csv('/content/drive/MyDrive/프로젝트응용(신동준, 이재훈, 최민규)/data/전처리/train_v2(결측_이상).csv')
df_test = pd.read_csv('/content/drive/MyDrive/프로젝트응용(신동준, 이재훈, 최민규)/data/전처리/test_v2(결측_이상).csv')
df_train.shape, df_test.shape

((32333, 21), (1656, 21))

## TRAVEL_MISSION_CHECK1, 2 숫자 밀기

In [ ]:
df_cd = pd.read_csv('/content/drive/MyDrive/프로젝트응용(신동준, 이재훈, 최민규)/data/압축해제/train/tc_codeb_코드B.csv')

In [ ]:
df_cd.loc[df_cd['cd_a'] == 'MIS']

,idx,cd_nm,cd_a,cd_b,cd_memo,cd_memo2,del_flag,order_num,ins_dt,edit_dt
105,1097,쇼핑,MIS,1,NaN,NaN,N,999,2022-07-27 16:26:52.000,NaN
106,1098,"테마파크, 놀이시설, 동/식물원 방문",MIS,2,NaN,NaN,N,999,2022-07-27 16:26:58.000,NaN
107,1099,역사 유적지 방문,MIS,3,NaN,NaN,N,999,2022-07-27 16:27:03.000,NaN
108,1100,시티투어,MIS,4,NaN,NaN,N,999,2022-07-27 16:27:08.000,NaN
109,1101,"야외 스포츠, 레포츠 활동",MIS,5,NaN,NaN,N,999,2022-07-27 16:27:14.000,NaN
110,1102,지역 문화예술/공연/전시시설 관람,MIS,6,NaN,NaN,N,999,2022-07-27 16:27:19.000,NaN
111,1103,유흥/오락(나이트라이프),MIS,7,NaN,NaN,N,999,2022-07-27 16:27:26.000,NaN
112,1104,캠핑,MIS,8,NaN,NaN,N,999,2022-07-27 16:27:31.000,NaN
113,1105,지역 축제/이벤트 참가,MIS,9,NaN,NaN,N,999,2022-07-27 16:27:37.000,NaN
114,1106,온천/스파,MIS,10,NaN,NaN,N,999,2022-07-27 16:27:43.000,NaN
115,1107,교육/체험 프로그램 참가,MIS,11,NaN,NaN,N,999,2022-07-27 16:27:48.000,NaN
116,1108,드라마 촬영지 방문,MIS,12,NaN,NaN,N,999,2022-07-27 16:27:57.000,NaN
117,1109,종교/성지 순례,MIS,13,NaN,NaN,N,999,2022-07-27 16:28:01.000,NaN
118,1110,Well-ness 여행,MIS,21,NaN,NaN,N,999,2022-07-27 16:28:07.000,NaN
119,1111,SNS 인생샷 여행,MIS,22,NaN,NaN,N,999,2022-07-27 16:28:11.000,NaN
120,1112,호캉스 여행,MIS,23,NaN,NaN,N,999,2022-07-27 16:28:16.000,NaN
121,1113,신규 여행지 발굴,MIS,24,NaN,NaN,N,999,2022-07-27 16:28:21.000,NaN
122,1114,반려동물 동반 여행,MIS,25,NaN,NaN,N,999,2022-07-27 16:28:26.000,NaN
123,1115,인플루언서 따라하기 여행,MIS,26,NaN,NaN,N,999,2022-07-27 16:28:34.000,NaN
124,1116,친환경 여행(플로깅 여행),MIS,27,NaN,NaN,N,999,2022-07-27 16:30:10.000,NaN
125,1117,등반 여행,MIS,28,NaN,NaN,N,999,2022-07-27 16:30:13.000,NaN

# 변환 딕셔너리

In [ ]:
# TRAVEL_MISSION_CHECK1, TRAVEL_MISSION_CHECK2에 대한 변환 딕셔너리
mission_check_labels = {
    1: "쇼핑",
    2: "테마파크, 놀이시설, 동/식물원 방문",
    3: "역사 유적지 방문",
    4: "시티투어",
    5: "야외 스포츠, 레포츠 활동",
    6: "지역 문화예술/공연/전시시설 관람",
    7: "유흥/오락(나이트라이프)",
    8: "캠핑",
    9: "지역 축제/이벤트 참가",
    10: "온천/스파",
    11: "교육/체험 프로그램 참가",
    12: "드라마 촬영지 방문",
    13: "종교/성지 순례",
    21: "Well-ness 여행",
    22: "SNS 인생샷 여행",
    23: "호캉스 여행",
    24: "신규 여행지 발굴",
    25: "반려동물 동반 여행",
    26: "인플루언서 따라하기 여행",
    27: "친환경 여행(플로깅 여행)",
    28: "등반 여행"
}

# TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3에 대한 변환 딕셔너리
motive_labels = {
    1.0: "일상적인 환경 및 역할에서의 탈출, 지루함 탈피",
    2.0: "쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식",
    3.0: "여행 동반자와의 친밀감 및 유대감 증진",
    4.0: "진정한 자아 찾기 또는 자신을 되돌아볼 기회 찾기",
    5.0: "SNS 사진 등록 등 과시",
    6.0: "운동, 건강 증진 및 충전",
    7.0: "새로운 경험 추구",
    8.0: "역사 탐방, 문화적 경험 등 교육적 동기"
}

# TRAVEL_MISSION_CHECK1, TRAVEL_MISSION_CHECK2 열의 값 변경
for column in ['TRAVEL_MISSION_CHECK1', 'TRAVEL_MISSION_CHECK2']:
    df_train[column] = df_train[column].map(mission_check_labels).fillna(df_train[column])

# TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3 열의 값 변경
for column in ['TRAVEL_MOTIVE_1', 'TRAVEL_MOTIVE_2', 'TRAVEL_MOTIVE_3']:
    df_train[column] = df_train[column].map(motive_labels).fillna(df_train[column])

df_train.loc[df_train['NTvsCT'] == 1, 'NTvsCT'] = "자연 선호"
df_train.loc[df_train['NTvsCT'] == 2, 'NTvsCT'] = "상관 없음"
df_train.loc[df_train['NTvsCT'] == 3, 'NTvsCT'] = "도시 선호"
df_train.loc[df_train['EXPLODvsCHPLOD'] == 1, 'EXPLODvsCHPLOD'] = "비싼숙소 선호"
df_train.loc[df_train['EXPLODvsCHPLOD'] == 2, 'EXPLODvsCHPLOD'] = "상관 없음"
df_train.loc[df_train['EXPLODvsCHPLOD'] == 3, 'EXPLODvsCHPLOD'] = "저렴한숙소 선호"
df_train.loc[df_train['RESTvsACT'] == 1, 'RESTvsACT'] = "휴식 선호"
df_train.loc[df_train['RESTvsACT'] == 2, 'RESTvsACT'] = "상관 없음"
df_train.loc[df_train['RESTvsACT'] == 3, 'RESTvsACT'] = "활동 선호"
df_train.loc[df_train['UNKvsK'] == 1, 'UNKvsK'] = "알려지지 않은 장소 선호"
df_train.loc[df_train['UNKvsK'] == 2, 'UNKvsK'] = "상관 없음"
df_train.loc[df_train['UNKvsK'] == 3, 'UNKvsK'] = "알려진장소 선호"

In [ ]:
df_train['TRAVEL_MOTIVE_3'].unique()

array(['쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식', 'SNS 사진 등록 등 과시',
       '일상적인 환경 및 역할에서의 탈출, 지루함 탈피', '진정한 자아 찾기 또는 자신을 되돌아볼 기회 찾기',
       '새로운 경험 추구', '운동, 건강 증진 및 충전', '역사 탐방, 문화적 경험 등 교육적 동기'],
      dtype=object)

In [ ]:
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 1, 'TRAVEL_MISSION_CHECK1'] = "쇼핑"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 2, 'TRAVEL_MISSION_CHECK1'] = "테마파크, 놀이시설, 동/식물원 방문"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 3, 'TRAVEL_MISSION_CHECK1'] = "역사 유적지 방문"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 4, 'TRAVEL_MISSION_CHECK1'] = "시티투어"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 5, 'TRAVEL_MISSION_CHECK1'] = "야외 스포츠, 레포츠 활동"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 6, 'TRAVEL_MISSION_CHECK1'] = "지역 문화예술/공연/전시시설 관람"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 7, 'TRAVEL_MISSION_CHECK1'] = "유흥/오락(나이트라이프)"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 8, 'TRAVEL_MISSION_CHECK1'] = "캠핑"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 9, 'TRAVEL_MISSION_CHECK1'] = "지역 축제/이벤트 참가"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 10, 'TRAVEL_MISSION_CHECK1'] = "온천/스파"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 11, 'TRAVEL_MISSION_CHECK1'] = "교육/체험 프로그램 참가"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 12, 'TRAVEL_MISSION_CHECK1'] = "드라마 촬영지 방문"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 13, 'TRAVEL_MISSION_CHECK1'] = "종교/성지 순례"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 21, 'TRAVEL_MISSION_CHECK1'] = "Well-ness 여행"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 22, 'TRAVEL_MISSION_CHECK1'] = "SNS 인생샷 여행"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 23, 'TRAVEL_MISSION_CHECK1'] = "호캉스 여행"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 24, 'TRAVEL_MISSION_CHECK1'] = "신규 여행지 발굴"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 25, 'TRAVEL_MISSION_CHECK1'] = "반려동물 동반 여행"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 26, 'TRAVEL_MISSION_CHECK1'] = "인플루언서 따라하기 여행"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 27, 'TRAVEL_MISSION_CHECK1'] = "친환경 여행(플로깅 여행)"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK1'] == 28, 'TRAVEL_MISSION_CHECK1'] = "등반 여행"

In [ ]:
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 1, 'TRAVEL_MISSION_CHECK2'] = "쇼핑"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 2, 'TRAVEL_MISSION_CHECK2'] = "테마파크, 놀이시설, 동/식물원 방문"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 3, 'TRAVEL_MISSION_CHECK2'] = "역사 유적지 방문"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 4, 'TRAVEL_MISSION_CHECK2'] = "시티투어"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 5, 'TRAVEL_MISSION_CHECK2'] = "야외 스포츠, 레포츠 활동"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 6, 'TRAVEL_MISSION_CHECK2'] = "지역 문화예술/공연/전시시설 관람"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 7, 'TRAVEL_MISSION_CHECK2'] = "유흥/오락(나이트라이프)"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 8, 'TRAVEL_MISSION_CHECK2'] = "캠핑"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 9, 'TRAVEL_MISSION_CHECK2'] = "지역 축제/이벤트 참가"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 10, 'TRAVEL_MISSION_CHECK2'] = "온천/스파"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 11, 'TRAVEL_MISSION_CHECK2'] = "교육/체험 프로그램 참가"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 12, 'TRAVEL_MISSION_CHECK2'] = "드라마 촬영지 방문"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 13, 'TRAVEL_MISSION_CHECK2'] = "종교/성지 순례"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 21, 'TRAVEL_MISSION_CHECK2'] = "Well-ness 여행"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 22, 'TRAVEL_MISSION_CHECK2'] = "SNS 인생샷 여행"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 23, 'TRAVEL_MISSION_CHECK2'] = "호캉스 여행"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 24, 'TRAVEL_MISSION_CHECK2'] = "신규 여행지 발굴"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 25, 'TRAVEL_MISSION_CHECK2'] = "반려동물 동반 여행"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 26, 'TRAVEL_MISSION_CHECK2'] = "인플루언서 따라하기 여행"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 27, 'TRAVEL_MISSION_CHECK2'] = "친환경 여행(플로깅 여행)"
# df_train.loc[df_train['TRAVEL_MISSION_CHECK2'] == 28, 'TRAVEL_MISSION_CHECK2'] = "등반 여행"

In [ ]:
df_train['TRAVEL_MISSION_CHECK1'].unique()

array(['종교/성지 순례', '쇼핑', '테마파크, 놀이시설, 동/식물원 방문', '교육/체험 프로그램 참가',
       'Well-ness 여행', '지역 축제/이벤트 참가', '시티투어', '등반 여행', '역사 유적지 방문',
       '지역 문화예술/공연/전시시설 관람', '친환경 여행(플로깅 여행)', 'SNS 인생샷 여행', '호캉스 여행',
       '야외 스포츠, 레포츠 활동', '인플루언서 따라하기 여행', '신규 여행지 발굴', '캠핑', '반려동물 동반 여행',
       '온천/스파', '유흥/오락(나이트라이프)', '드라마 촬영지 방문'], dtype=object)

In [ ]:
df_train['TRAVEL_MISSION_CHECK2'].unique()

array(['역사 유적지 방문', 'SNS 인생샷 여행', '지역 문화예술/공연/전시시설 관람', '인플루언서 따라하기 여행',
       '쇼핑', '등반 여행', '신규 여행지 발굴', '친환경 여행(플로깅 여행)', '시티투어', '반려동물 동반 여행',
       '테마파크, 놀이시설, 동/식물원 방문', '드라마 촬영지 방문', 'Well-ness 여행', '종교/성지 순례',
       '교육/체험 프로그램 참가', '지역 축제/이벤트 참가', '호캉스 여행', '온천/스파',
       '유흥/오락(나이트라이프)', '야외 스포츠, 레포츠 활동', '캠핑'], dtype=object)

In [ ]:
# # TRAVEL_MOTIVE_1
# df_train.loc[df_train['TRAVEL_MOTIVE_1'] == 1.0, 'TRAVEL_MOTIVE_1'] = "일상적인 환경 및 역할에서의 탈출, 지루함 탈피"
# df_train.loc[df_train['TRAVEL_MOTIVE_1'] == 2.0, 'TRAVEL_MOTIVE_1'] = "쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식"
# df_train.loc[df_train['TRAVEL_MOTIVE_1'] == 3.0, 'TRAVEL_MOTIVE_1'] = "여행 동반자와의 친밀감 및 유대감 증진"
# df_train.loc[df_train['TRAVEL_MOTIVE_1'] == 4.0, 'TRAVEL_MOTIVE_1'] = "진정한 자아 찾기 또는 자신을 되돌아볼 기회 찾기"
# df_train.loc[df_train['TRAVEL_MOTIVE_1'] == 5.0, 'TRAVEL_MOTIVE_1'] = "SNS 사진 등록 등 과시"
# df_train.loc[df_train['TRAVEL_MOTIVE_1'] == 6.0, 'TRAVEL_MOTIVE_1'] = "운동, 건강 증진 및 충전"
# df_train.loc[df_train['TRAVEL_MOTIVE_1'] == 7.0, 'TRAVEL_MOTIVE_1'] = "새로운 경험 추구"
# df_train.loc[df_train['TRAVEL_MOTIVE_1'] == 8.0, 'TRAVEL_MOTIVE_1'] = "역사 탐방, 문화적 경험 등 교육적 동기"
# # TRAVEL_MOTIVE_2
# df_train.loc[df_train['TRAVEL_MOTIVE_2'] == 1.0, 'TRAVEL_MOTIVE_2'] = "일상적인 환경 및 역할에서의 탈출, 지루함 탈피"
# df_train.loc[df_train['TRAVEL_MOTIVE_2'] == 2.0, 'TRAVEL_MOTIVE_2'] = "쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식"
# df_train.loc[df_train['TRAVEL_MOTIVE_2'] == 3.0, 'TRAVEL_MOTIVE_2'] = "여행 동반자와의 친밀감 및 유대감 증진"
# df_train.loc[df_train['TRAVEL_MOTIVE_2'] == 4.0, 'TRAVEL_MOTIVE_2'] = "진정한 자아 찾기 또는 자신을 되돌아볼 기회 찾기"
# df_train.loc[df_train['TRAVEL_MOTIVE_2'] == 5.0, 'TRAVEL_MOTIVE_2'] = "SNS 사진 등록 등 과시"
# df_train.loc[df_train['TRAVEL_MOTIVE_2'] == 6.0, 'TRAVEL_MOTIVE_2'] = "운동, 건강 증진 및 충전"
# df_train.loc[df_train['TRAVEL_MOTIVE_2'] == 7.0, 'TRAVEL_MOTIVE_2'] = "새로운 경험 추구"
# df_train.loc[df_train['TRAVEL_MOTIVE_2'] == 8.0, 'TRAVEL_MOTIVE_2'] = "역사 탐방, 문화적 경험 등 교육적 동기"
# # TRAVEL_MOTIVE_3
# df_train.loc[df_train['TRAVEL_MOTIVE_3'] == 1.0, 'TRAVEL_MOTIVE_3'] = "일상적인 환경 및 역할에서의 탈출, 지루함 탈피"
# df_train.loc[df_train['TRAVEL_MOTIVE_3'] == 2.0, 'TRAVEL_MOTIVE_3'] = "쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식"
# df_train.loc[df_train['TRAVEL_MOTIVE_3'] == 3.0, 'TRAVEL_MOTIVE_3'] = "여행 동반자와의 친밀감 및 유대감 증진"
# df_train.loc[df_train['TRAVEL_MOTIVE_3'] == 4.0, 'TRAVEL_MOTIVE_3'] = "진정한 자아 찾기 또는 자신을 되돌아볼 기회 찾기"
# df_train.loc[df_train['TRAVEL_MOTIVE_3'] == 5.0, 'TRAVEL_MOTIVE_3'] = "SNS 사진 등록 등 과시"
# df_train.loc[df_train['TRAVEL_MOTIVE_3'] == 6.0, 'TRAVEL_MOTIVE_3'] = "운동, 건강 증진 및 충전"
# df_train.loc[df_train['TRAVEL_MOTIVE_3'] == 7.0, 'TRAVEL_MOTIVE_3'] = "새로운 경험 추구"
# df_train.loc[df_train['TRAVEL_MOTIVE_3'] == 8.0, 'TRAVEL_MOTIVE_3'] = "역사 탐방, 문화적 경험 등 교육적 동기"

In [ ]:
df_train['TRAVEL_MOTIVE_1'].unique()

array(['새로운 경험 추구', '일상적인 환경 및 역할에서의 탈출, 지루함 탈피', 'SNS 사진 등록 등 과시',
       '쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식', '운동, 건강 증진 및 충전',
       '역사 탐방, 문화적 경험 등 교육적 동기', '진정한 자아 찾기 또는 자신을 되돌아볼 기회 찾기'],
      dtype=object)

In [ ]:
df_train['TRAVEL_MOTIVE_2'].unique()

array(['역사 탐방, 문화적 경험 등 교육적 동기', 'SNS 사진 등록 등 과시',
       '일상적인 환경 및 역할에서의 탈출, 지루함 탈피', '새로운 경험 추구',
       '쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식', '운동, 건강 증진 및 충전',
       '진정한 자아 찾기 또는 자신을 되돌아볼 기회 찾기'], dtype=object)

In [ ]:
df_train['TRAVEL_MOTIVE_3'].unique()

array(['쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식', 'SNS 사진 등록 등 과시',
       '일상적인 환경 및 역할에서의 탈출, 지루함 탈피', '진정한 자아 찾기 또는 자신을 되돌아볼 기회 찾기',
       '새로운 경험 추구', '운동, 건강 증진 및 충전', '역사 탐방, 문화적 경험 등 교육적 동기'],
      dtype=object)

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32333 entries, 0 to 32332
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   AGE_GRP                32333 non-null  float64
 1   GENDER                 32333 non-null  object
 2   TRAVEL_MONTH           32333 non-null  int64
 3   TRAVEL_PERIOD          32333 non-null  int64
 4   NTvsCT                 32333 non-null  object
 5   EXPLODvsCHPLOD         32333 non-null  object
 6   RESTvsACT              32333 non-null  object
 7   UNKvsK                 32333 non-null  object
 8   MVMN_NM                32333 non-null  object
 9   TRAVEL_MISSION_CHECK1  32333 non-null  object
 10  TRAVEL_MISSION_CHECK2  32333 non-null  object
 11  TRAVEL_MOTIVE_1        32333 non-null  object
 12  TRAVEL_MOTIVE_2        32333 non-null  object
 13  TRAVEL_MOTIVE_3        32333 non-null  object
 14  budget                 32333 non-null  float64
 15  VISIT_AREA_NM          32333 non-null  object
 16  DGSTFN                 32333 non-null  float64
 17  ROAD_NM_ADDR           26246 non-null  object
 18  LOTNO_ADDR             29985 non-null  object
 19  X_COORD                30207 non-null  float64
 20  Y_COORD                30207 non-null  float64
dtypes: float64(5), int64(2), object(14)
memory usage: 5.2+ MB

In [ ]:
df_train.loc[df_train['NTvsCT'] == 1, 'NTvsCT'] = "자연 선호"
df_train.loc[df_train['NTvsCT'] == 2, 'NTvsCT'] = "상관 없음"
df_train.loc[df_train['NTvsCT'] == 3, 'NTvsCT'] = "도시 선호"
df_train.loc[df_train['EXPLODvsCHPLOD'] == 1, 'EXPLODvsCHPLOD'] = "비싼숙소 선호"
df_train.loc[df_train['EXPLODvsCHPLOD'] == 2, 'EXPLODvsCHPLOD'] = "상관 없음"
df_train.loc[df_train['EXPLODvsCHPLOD'] == 3, 'EXPLODvsCHPLOD'] = "저렴한숙소 선호"
df_train.loc[df_train['RESTvsACT'] == 1, 'RESTvsACT'] = "휴식 선호"
df_train.loc[df_train['RESTvsACT'] == 2, 'RESTvsACT'] = "상관 없음"
df_train.loc[df_train['RESTvsACT'] == 3, 'RESTvsACT'] = "활동 선호"
df_train.loc[df_train['UNKvsK'] == 1, 'UNKvsK'] = "알려지지 않은 장소 선호"
df_train.loc[df_train['UNKvsK'] == 2, 'UNKvsK'] = "상관 없음"
df_train.loc[df_train['UNKvsK'] == 3, 'UNKvsK'] = "알려진장소 선호"

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32333 entries, 0 to 32332
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   AGE_GRP                32333 non-null  float64
 1   GENDER                 32333 non-null  object
 2   TRAVEL_MONTH           32333 non-null  int64
 3   TRAVEL_PERIOD          32333 non-null  int64
 4   NTvsCT                 32333 non-null  object
 5   EXPLODvsCHPLOD         32333 non-null  object
 6   RESTvsACT              32333 non-null  object
 7   UNKvsK                 32333 non-null  object
 8   MVMN_NM                32333 non-null  object
 9   TRAVEL_MISSION_CHECK1  32333 non-null  object
 10  TRAVEL_MISSION_CHECK2  32333 non-null  object
 11  TRAVEL_MOTIVE_1        32333 non-null  object
 12  TRAVEL_MOTIVE_2        32333 non-null  object
 13  TRAVEL_MOTIVE_3        32333 non-null  object
 14  budget                 32333 non-null  float64
 15  VISIT_AREA_NM          32333 non-null  object
 16  DGSTFN                 32333 non-null  float64
 17  ROAD_NM_ADDR           26246 non-null  object
 18  LOTNO_ADDR             29985 non-null  object
 19  X_COORD                30207 non-null  float64
 20  Y_COORD                30207 non-null  float64
dtypes: float64(5), int64(2), object(14)
memory usage: 5.2+ MB

In [ ]:
df_train

,AGE_GRP,GENDER,TRAVEL_MONTH,TRAVEL_PERIOD,NTvsCT,EXPLODvsCHPLOD,RESTvsACT,UNKvsK,MVMN_NM,TRAVEL_MISSION_CHECK1,...,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,TRAVEL_MOTIVE_3,budget,VISIT_AREA_NM,DGSTFN,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD
0,60.0,여,10,3,상관 없음,비싼숙소 선호,상관 없음,상관 없음,대중교통 등,종교/성지 순례,...,새로운 경험 추구,"역사 탐방, 문화적 경험 등 교육적 동기","쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식",57100.0,수도국산 달동네박물관,5.0,인천 동구 솔빛로 51,인천 동구 송현동 163,126.639136,37.477481
1,60.0,여,10,3,상관 없음,비싼숙소 선호,상관 없음,상관 없음,대중교통 등,종교/성지 순례,...,새로운 경험 추구,"역사 탐방, 문화적 경험 등 교육적 동기","쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식",57100.0,인천내리교회,5.0,인천 중구 우현로67번길 3-1,인천 중구 내동 29,126.628812,37.473755
2,60.0,여,10,3,상관 없음,비싼숙소 선호,상관 없음,상관 없음,대중교통 등,종교/성지 순례,...,새로운 경험 추구,"역사 탐방, 문화적 경험 등 교육적 동기","쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식",57100.0,부평문화의거리,4.0,인천 부평구 광장로 6,인천 부평구 부평동 224-1,126.724278,37.494163
3,60.0,여,10,3,상관 없음,비싼숙소 선호,상관 없음,상관 없음,대중교통 등,종교/성지 순례,...,새로운 경험 추구,"역사 탐방, 문화적 경험 등 교육적 동기","쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식",57100.0,인천배다리헌책방거리,4.0,NaN,인천 동구 금곡동 87-6,126.636406,37.472559
4,60.0,여,10,3,상관 없음,비싼숙소 선호,상관 없음,상관 없음,대중교통 등,종교/성지 순례,...,새로운 경험 추구,"역사 탐방, 문화적 경험 등 교육적 동기","쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식",57100.0,인천개항장 근대건축전시관,5.0,인천 중구 신포로23번길 77,인천 중구 중앙동2가 24-1,126.621165,37.472945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32328,20.0,여,9,1,자연 선호,비싼숙소 선호,휴식 선호,알려지지 않은 장소 선호,대중교통 등,등반 여행,...,"쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식",진정한 자아 찾기 또는 자신을 되돌아볼 기회 찾기,"일상적인 환경 및 역할에서의 탈출, 지루함 탈피",15000.0,물영아리,4.0,NaN,제주특별자치도 서귀포시 남원읍 수망리 산 188,126.692064,33.368395
32329,50.0,여,9,1,상관 없음,비싼숙소 선호,활동 선호,알려지지 않은 장소 선호,대중교통 등,"야외 스포츠, 레포츠 활동",...,새로운 경험 추구,"일상적인 환경 및 역할에서의 탈출, 지루함 탈피","운동, 건강 증진 및 충전",33500.0,꼬스뗀뇨,3.0,제주특별자치도 제주시 구좌읍 해맞이해안로 2080,제주특별자치도 제주시 구좌읍 종달리 150,126.905244,33.509868
32330,50.0,여,9,1,상관 없음,비싼숙소 선호,활동 선호,알려지지 않은 장소 선호,대중교통 등,"야외 스포츠, 레포츠 활동",...,새로운 경험 추구,"일상적인 환경 및 역할에서의 탈출, 지루함 탈피","운동, 건강 증진 및 충전",33500.0,마이 피기 팬트리,4.0,제주특별자치도 제주시 구좌읍 하도13길 6,제주특별자치도 제주시 구좌읍 하도리 1091-5,126.888132,33.508700
32331,50.0,여,9,1,상관 없음,비싼숙소 선호,활동 선호,알려지지 않은 장소 선호,대중교통 등,"야외 스포츠, 레포츠 활동",...,새로운 경험 추구,"일상적인 환경 및 역할에서의 탈출, 지루함 탈피","운동, 건강 증진 및 충전",33500.0,월정리 해수욕장,4.0,NaN,제주특별자치도 제주시 구좌읍 월정리 33-3,126.795805,33.556469
32332,50.0,여,9,1,상관 없음,비싼숙소 선호,활동 선호,알려지지 않은 장소 선호,대중교통 등,"야외 스포츠, 레포츠 활동",...,새로운 경험 추구,"일상적인 환경 및 역할에서의 탈출, 지루함 탈피","운동, 건강 증진 및 충전",33500.0,민경이네어등포해녀촌,4.0,제주특별자치도 제주시 구좌읍 해맞이해안로 830,제주특별자치도 제주시 구좌읍 행원리 102,126.825773,33.553735

In [ ]:
dd

NameError: name 'dd' is not defined

# 데이터 정규분포형태 만들어보기

In [ ]:
from scipy.stats import boxcox

# Box-Cox 변환 (데이터에 0 이상의 값만 존재해야 함)
budget_transformed, _ = boxcox(df['budget'] + 1)  # 만약 값이 0일 경우 +1을 해줘야 함
df['budget'] = budget_transformed

# df_train['DGSTFN_transformed2'] = np.sqrt(df_train['DGSTFN'])

In [ ]:
# # 히스토그램 시각화
# plt.figure(figsize=(12, 6))

# # Box-Cox 변환 히스토그램 (DGSTFN_transformed1)
# plt.subplot(1, 2, 1)
# sns.histplot(df_train['DGSTFN_transformed1'], bins=30, kde=True)
# plt.title('Histogram of Box-Cox Transformed DGSTFN (Transformed1)')
# plt.xlabel('DGSTFN_transformed1')

# # 제곱근 변환 히스토그램 (DGSTFN_transformed2)
# plt.subplot(1, 2, 2)
# sns.histplot(df_train['DGSTFN_transformed2'], bins=30, kde=True)
# plt.title('Histogram of Square Root Transformed DGSTFN (Transformed2)')
# plt.xlabel('DGSTFN_transformed2')

# plt.tight_layout()
# plt.show()

In [ ]:
# from sklearn.utils import resample

# # 1~3 구간과 4~5 구간으로 데이터 분리
# low_satisfaction = df_train[df_train['DGSTFN'] <= 4]
# high_satisfaction = df_train[df_train['DGSTFN'] > 4]

# # 1~3 구간 데이터 업샘플링
# low_satisfaction_upsampled = resample(low_satisfaction,
#                                       replace=True,
#                                       n_samples=len(high_satisfaction),  # 4~5 구간과 균형 맞추기
#                                       random_state=42)

# # 업샘플링 후 데이터 재결합
# df_balanced = pd.concat([low_satisfaction_upsampled, high_satisfaction])

# # 만족도 히스토그램 시각화
# plt.figure(figsize=(8, 6))
# sns.histplot(df_balanced['DGSTFN'], bins=5, kde=True)
# plt.title("Histogram of Balanced DGSTFN after Upsampling")
# plt.xlabel("DGSTFN")
# plt.ylabel("Frequency")
# plt.show()

In [ ]:
1656/32333

In [ ]:
df_train.info()

In [ ]:
# from sklearn.preprocessing import LabelEncoder

# # 데이터프레임을 df로 가정
# label_encoder = LabelEncoder()

# # object 타입의 칼럼만 선택하여 레이블 인코딩 수행
# for col in df_train.select_dtypes(include=['object']).columns:
#     df_train[col] = label_encoder.fit_transform(df_train[col])

# for col in df_test.select_dtypes(include=['object']).columns:
#     df_test[col] = label_encoder.fit_transform(df_test[col])

In [ ]:
df_train.drop(columns=['ROAD_NM_ADDR', 'LOTNO_ADDR', 'X_COORD', 'Y_COORD'], inplace=True)
df_test.drop(columns=['ROAD_NM_ADDR', 'LOTNO_ADDR', 'X_COORD', 'Y_COORD'], inplace=True)

# RandomForest

In [ ]:
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.metrics import mean_squared_error, r2_score

# # 훈련 및 테스트 데이터 설정
# X_train = df_train.drop(columns=['DGSTFN'])  # 타겟 변수를 제외한 특성 데이터 (훈련)
# y_train = df_train['DGSTFN']  # 타겟 변수 (훈련)

# X_test = df_test.drop(columns=['DGSTFN'])  # 타겟 변수를 제외한 특성 데이터 (테스트)
# y_test = df_test['DGSTFN']  # 타겟 변수 (테스트)

# # Random Forest Regressor 모델 초기화 및 학습
# model = RandomForestRegressor(n_estimators=10000, max_depth=25, random_state=42)
# model.fit(X_train, y_train)

# # 예측 수행
# y_pred = model.predict(X_test)

# # 성능 평가
# mse = mean_squared_error(y_test, y_pred)
# r2 = r2_score(y_test, y_pred)

# print("Mean Squared Error (MSE):", mse)
# print("R-squared (R2):", r2)

# Catboost - 1

In [ ]:
pip install catboost

In [ ]:
# from catboost import CatBoostRegressor
# from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# # 특성 데이터와 타겟 변수 설정
# X_train = df_train.drop(columns=['DGSTFN'])  # 타겟 변수를 제외한 훈련 데이터
# y_train = df_train['DGSTFN']  # 훈련 데이터의 타겟 변수

# X_test = df_test.drop(columns=['DGSTFN'])  # 타겟 변수를 제외한 테스트 데이터
# y_test = df_test['DGSTFN']  # 테스트 데이터의 타겟 변수

# # 범주형 특성 지정 (예시)
# cat_features = ['GENDER', 'MVMN_NM', 'VISIT_AREA_NM']  # 범주형 변수가 있는 경우 해당 열 이름을 지정

# # CatBoostRegressor 모델 초기화
# model = CatBoostRegressor(iterations=2000,
#                           learning_rate=0.01,
#                           depth=10,
#                           cat_features=cat_features,  # 범주형 변수 설정
#                           random_seed=42,
#                           verbose=100)

# # 모델 학습
# model.fit(X_train, y_train)

# # 예측 수행
# y_train_pred = model.predict(X_train)
# y_test_pred = model.predict(X_test)

# # MAE, MSE, RMSE 계산
# train_mae = mean_absolute_error(y_train, y_train_pred)
# test_mae = mean_absolute_error(y_test, y_test_pred)

# train_mse = mean_squared_error(y_train, y_train_pred)
# test_mse = mean_squared_error(y_test, y_test_pred)

# train_rmse = np.sqrt(train_mse)
# test_rmse = np.sqrt(test_mse)

# # Adjusted R-squared 계산 함수
# def adjusted_r2(y_true, y_pred, X):
#     r2 = r2_score(y_true, y_pred)
#     n = X.shape[0]  # 샘플 수
#     p = X.shape[1]  # 특성 수
#     return 1 - (1 - r2) * (n - 1) / (n - p - 1)

# # R-squared 및 Adjusted R-squared 계산
# train_r2 = r2_score(y_train, y_train_pred)
# test_r2 = r2_score(y_test, y_test_pred)

# train_adj_r2 = adjusted_r2(y_train, y_train_pred, X_train)
# test_adj_r2 = adjusted_r2(y_test, y_test_pred, X_test)

# # 결과 출력
# results = {
#     "Train Data": {
#         "MAE": train_mae,
#         "MSE": train_mse,
#         "RMSE": train_rmse,
#         "R-squared": train_r2,
#         "Adjusted R-squared": train_adj_r2,
#     },
#     "Test Data": {
#         "MAE": test_mae,
#         "MSE": test_mse,
#         "RMSE": test_rmse,
#         "R-squared": test_r2,
#         "Adjusted R-squared": test_adj_r2,
#     }
# }

# print(results)

# Catboost - 2

In [ ]:
df_train.info()

In [ ]:
categorical_features_names = [
    'GENDER', 'MVMN_NM', 'TRAVEL_MOTIVE_1', 'TRAVEL_MOTIVE_2', 'TRAVEL_MOTIVE_3', 'VISIT_AREA_NM'
]
df_train[categorical_features_names[2:-1]] = df_train[categorical_features_names[2:-1]].astype(int)
df_train.shape

In [ ]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(df_train, test_size = 0.2, random_state=42)

train_df.shape, val_df.shape

In [ ]:
from catboost import CatBoostRegressor, Pool

train_pool = Pool(train_df.drop(['DGSTFN'], axis=1),
                  label = train_df['DGSTFN'],
                  cat_features = categorical_features_names)

val_pool = Pool(val_df.drop(['DGSTFN'], axis=1),
                 label = val_df['DGSTFN'],
                 cat_features = categorical_features_names)

In [ ]:
model = CatBoostRegressor(
    loss_function = 'RMSE',
    eval_metric='MAE',
    task_type='GPU',
    depth=10,
    learning_rate=0.01,
    n_estimators=5000
)
model.fit(
    train_pool,
    eval_set = val_pool,
    verbose=500,
    plot=True
)

# 데이터 합쳐보기